### ISSUE TITLE
[Idea] Hide label Options

### ISSUE THREAD

**Issue by SylisMC** [SFort/MC-noplayerlabels#1]
Hey! Handy mod, love it, some options would be a nice touch if you feel like juicing it up a bit

- [x]  Wall sight | only show player names when they are behind walls (makes it easier to find your friends when exploring together,
- [x] hide friendly | Only hide players on your team
- toggle hide | Show names when shifting

Thanks for all your hard work

**Comment by SFort** [comment]
Sorry for some reason github unsubscibed me from updates on just this repo
I only just found out by chance since i'm updating the mod

the sneaking just seems like a wierd feature so not adding
other two have been added
