### ISSUE TITLE
Forge version!

### ISSUE THREAD

**Issue by ghost** [SFort/MC-noplayerlabels#2]
I really want this mod on Forge!

**Comment by SFort** [comment]
I might take another look at forge
but for now don't have the time 
soo all i can do is give you the good old: "pull requests are welcome, try it yourself"

**Comment by SFort** [comment]
Had a bit of time took a look.
Turns out PlayerEntityRender is handeled by forges event sys
(Which means forge blocks me from re-using the current code)
i don't really want to learn forge events or rewrite the mod to fit them
