### ISSUE TITLE
Config Wiki?

### ISSUE THREAD

**Issue by VoidLock92** [SFort/MC-noplayerlabels#4]
I know it is a somewhat simple mod config wise, but it would be very helpful to have a wiki page on here just explaining how to change the settings in the config and what they do. Mainly I am having issue setting the visibility distance. 

16.0
^-Show when nearby  [0.0] 0.0 - ...
on
^-Hide when behind Walls [off] on | invert | off
on
^-Show when on the same team [off] on | invert | off
null

Not sure what invert does, and I assume the 16 I set will show names for people not behind walls and within 1 chunk distance but this is not how it is functioning in game.

Any help would be awesome thanks!

**Comment by SFort** [comment]
0 means player labels will be hidden regardless of distance
any other value and the player needs to be that close to see the name
```  ^-Show when nearby [0.0] 0.0 - ... ```
on:     hide names whe the player is not vissable (aka behind a wall)
invert: hide names when the player is visable
off:    ignore visability
```  ^-Hide when behind Walls [off] on | invert | off ```
on:     require players to be on the same team to see each others name
invert: require players to not me on the same team
off:    ignore teams
```  ^-Show when on the same team [off] on | invert | off  ```

so with your current setting a player needs 
- to be within 16 blocks
- be visable (not behind any block) 
- be on the same team [see mc wiki](https://minecraft.fandom.com/wiki/Commands/team)

**Comment by VoidLock92** [comment]
OHH ok so the show same team setting means it will only show if they are SAME team, I thought it was saying it will always show team tags. I understand now. So I want them to be within 16 blocks, be visible and not be on same team so I just need to change same team to off and should be good.

Thanks so much! I will give this a try now!

**Comment by VoidLock92** [comment]
Yup works good now with those settings :) Thanks for explaining to me!
