### ISSUE TITLE
Crashes when distance 5 and see through walls on

### ISSUE THREAD

**Issue by KapsiF** [SFort/MC-noplayerlabels#5]
crashes with:
When config set as title
java.lang.IllegalStateException: Pose stack not empty  at net.minecraft.class_761.method_22979(class_761.java:1558)  at net.minecraft.class_761.method_22710(class_761.java:1321)  at net.minecraft.class_757.method_3188(class_757.java:1039)  at net.minecraft.class_757.method_3192(class_757.java:816)  at net.minecraft.class_310.method_1523(class_310.java:1177)  at net.minecraft.class_310.method_1514(class_310.java:768)  at net.minecraft.client.main.Main.method_44604(Main.java:244)  at net.minecraft.client.main.Main.main(Main.java:51)  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)  at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SFort** [comment]
what mod version / minecraft version
did you try with only the mod installed in case it's a conflict

**Comment by KapsiF** [comment]
1.19.2 it was the newest so 2.1.0
Yes, all player's were crashing with these config settings when they got too close to another player

**Comment by SFort** [comment]
tested on 1.19.2/2.1.0 and 2.1.1 not getting the issue.
and this mod shouldn't cause anything like that clash log.

my guess would be it's another mod causing it, but you said you tried with just this sooo i have no idea.

good luck, i'll try and help if you need anything, but i can't fix it if i can't even make it happen.

https://user-images.githubusercontent.com/1879846/228871466-92207133-78cb-462e-9a05-6224aaa14310.mp4

**Comment by KapsiF** [comment]
Yea idk. It works after I downgraded my modpack then went mod by mod and it fixed itself
