### ISSUE TITLE
1.20 player labels don't show at all

### ISSUE THREAD

**Issue by zndrmn** [SFort/MC-noplayerlabels#6]
This is the config I'm using, default also shows no nametags on players
Also shows no labels with shaders off
```ini
; Show name tag when nearby. [0.0] 0.0+
visibleDistance=13.0
; Hide name tag when behind walls. [off] on | invert | off
hideBehindWall=on
; Show name tag when on the same team. [off] on | invert | off
showTeamMembers=on
```

![2023-06-30_04 37 15](https://github.com/SFort/MC-noplayerlabels/assets/77690119/2c7f78ae-330d-4efa-bfdf-ea274dc8b172)

**Comment by SFort** [comment]
~~are you on the same team as the other player? [mc wiki](https://minecraft.fandom.com/wiki/Commands/team)
this seams to confuse a fair bit of players but `showTeamMembers=on` means you need to be on the same team~~

seams like i made a mistake and the viewDistance is inverted (so you can see from far away but not close up)
